name: 'KiCad Picture Generator'
description: 'Generate photos of the schematic, PCB layout, and the 3D rendering of the PCB'
inputs:
  project-path:
    description: 'The path to the KiCad project'
    required: true
    default: './'
  project-name:
    description: 'Name of the KiCad project (the string before .kicad_pro/.kicad_sch/.kicad_pcb)'
    required: true
  output-path:
    description: 'The path where the generated photos will be output'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      shell: bash
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases
        sudo apt update --yes
        sudo apt install --install-recommends --yes kicad
    - name: Generate the schematic image
      shell: bash
      run: kicad-cli sch export svg $PROJECT_PATH$PROJECT_NAME.kicad_sch -o "$OUTPUT_PATH"
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
        PROJECT_NAME: ${{ inputs.project-name }}
        OUTPUT_PATH: ${{ inputs.output-path }}

    - name: Generate the PCB image
      shell: bash
      run: kicad-cli pcb export svg $PROJECT_PATH$PROJECT_NAME.kicad_pcb -l "F.Cu,B.Cu,F.Silkscreen,B.Silkscreen,Edge.Cuts" -o "$OUTPUT_PATH$PROJECT_NAME-pcb.svg"
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
        PROJECT_NAME: ${{ inputs.project-name }}
        OUTPUT_PATH: ${{ inputs.output-path }}

    - name: Push changes
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        add: .
        message: 'Update KiCad Image'